@startuml diagrama clases
title TO DO list

interface Builder #Thistle;header:444 {
    reset(): void;
    setTitulo(titulo: string): this;
    setDescripcion(descripcion: string): this;
    setFechaCreacion(fechaCreacion: Date): this;
    setFechaVencimiento(fechaVencimiento: Date): this;
    setFechaFinalizacion(fechaFinalizacion: Date): this;
    setPrioridad(prioridad: prioridad): this;
    setCategoria(categoria: categoria): this;
    setEtiquetas(etiquetas: string[]): this;
    construirTarea(): Tarea;
}

class Tarea #TECHNOLOGY;header:444{
    - titulo: string;
    - descripcion: string;
    - fechaCreacion: Date;
    - fechaVencimiento: Date| null;
    - fechaFinalizacion: Date | null;
    - prioridad: prioridad | null ;
    - completado: boolean;
    - porcentajeAvance: number;
    - categoria: categoria | null;
    - etiqueta: string[];
    + setters y getters()
    + agregarEtiqueta(etiqueta: string): void;
    + borrarEtiqueta(etiqueta: string): string | void;
}

class ConstructorTarea #TECHNOLOGY;header:444 implements Builder {
    - tarea: Tarea;
    +reset(): void ;
    +setTitulo(titulo: string): this ;
    +setDescripcion(descripcion: string): this ;
    +setFechaCreacion(fechaCreacion: Date): this ;
    +setFechaVencimiento(fechaVencimiento: Date): this ;
    +setFechaFinalizacion(fechaFinalizacion: Date): this ;
    +setPrioridad(prioridad: prioridad): this ;
    +setCompletado(completado: boolean): this ;
    +setPorcentajeAvance(porcentajeAvance: number): this ;
    +setCategoria(categoria: categoria): this ;
    +setEtiquetas(etiquetas: string[]): this ;
    +construirTarea(): Tarea;
}

class Director #TECHNOLOGY;header:444 {
    - builder: Builder;
    - lista: ToDoLista;
    + setBuilder(builder: Builder): void;
    + construirTarea(configurar: () => void): Tarea;
}

enum prioridad #LightSalmon;header:444{
    baja,
    media,
    alta
}

enum categorias #LightSalmon;header:444{
    Trabajo,
    Personal,
    Familia,
    Estudio
}
class ToDoLista #TECHNOLOGY;header:444 {
    - listaTareas: Tarea[];
    - listaTareasCompletadas: Tarea[];
    - listaTareasPendientes: Tarea[];
    + agregarAListas(tarea: Tarea): void;
    + cambiarDeListas(tarea: Tarea): void;
    + borrarDeListas(titulo: string): void;
    + borrarPorTitulo(titulo: string): void;
    + getTareaDeLista(titulo: string): Tarea | undefined;
    + getListaTareas(): Tarea[];
    + getTareasCompletadas(): Tarea[];
    + getTareasPendientes(): Tarea[];
    + getTarea(titulo: string): Tarea;
    + setListaTareas(listaTareas: Tarea[]): void;
}

class Busqueda #TECHNOLOGY;header:444 {
    + busquedaPorTitulo(tareas: Tarea[], titulo: string): Tarea[];
    + busquedaPorFecha(tareas: Tarea[], fecha: Date): Tarea[];
    + busquedaPorPrioridad(tareas: Tarea[], prioridad: prioridad): Tarea[];
    + busquedaPorCategoria(tareas: Tarea[], categoria: categoria): Tarea[];
    + busquedaPorEtiqueta(tareas: Tarea[], etiqueta: string): Tarea[];
}
class Ordenamiento #TECHNOLOGY;header:444 {
    + ordenarPorTitulo(listaDesordenada: Tarea[], ascendiente: boolean): Tarea[];
    + ordenarPorFecha(listaDesordenada: Tarea[], ascendiente: boolean): Tarea[];
    + ordenarPorPrioridad(listaDesordenada: Tarea[], ascendiente: boolean): Tarea[];
    + ordenarPorEtiquietas(listaDesordenada: Tarea[], ascendiente: boolean): Tarea[];
}
class CalculadoraEstadistica #TECHNOLOGY;header:444 {
    - numeroTareasCompletadas: number;
    - numeroTareasTotales: number;
    - listadoTIempoDedicadoXTarea: map<Tarea, number>;
    + calcularTasa(listaTareas: ToDoLista): number;
    + calcularTiempoDedicado(listaTareas: ToDoLista):map<Tarea, number>;
}

class Persistencia #TECHNOLOGY;header:444 {
    + constructorTarea: ConstructorTarea;
    + lista: ToDoLista;
    + director: Director;
    + static async obtenerBaseDeDatos(): Promise<Tarea[]>;
    + static async guardarBaseDeDatos(data: string): Promise<void>;
}
exception tareaInexistenteError #LightCoral;header:444{}

exception EtiquetaInexistenteError #LightCoral;header:444{}
'relaciones
    skinparam ranksep 100
'cambia el largo de las flechas
    skinparam nodesep 100
'cambia la distancia entre los cuadrados
    categorias .r.> Tarea::categoria
    Tarea .u.> ConstructorTarea
    Tarea ..* ToDoLista
    prioridad .l.> Tarea::prioridad
    Tarea::borrarEtiqueta <.r. EtiquetaInexistenteError
    ToDoLista::borrarDeLista <.l. tareaInexistenteError
    ToDoLista::borrarPorTitulo <.l. tareaInexistenteError
    ToDoLista .d.> CalculadoraEstadistica
    ToDoLista .d.> Busqueda
    ToDoLista .d.> Ordenamiento
    ToDoLista .d.> Persistencia
    Director .r.> Builder
'notas
'diseño
        'colores de clases
            /'
            clase: #TECHNOLOGY;header:444
            clase: abstracta #LightCyan;header:444
            interfaz: #Thistle;header:444
            enums: #LightSalmon;header:444
            excepciones: #LightCoral;header:444
            '/
            skinparam roundcorner 20
        'cambia las esquinas de las clases para hacerlas mas redondeadas
            skinparam classFontColor automatic
        'cambia el color de fuente de todas las clases asi se ve en blanco sobre el fondo oscuro
    @enduml